course = "Chess for Beginners "
print(course)
print(course.find("C"))
print(course.find("h"))
print(course.find("e"))
print(course.find("s"))
print(course.find("s"))
print(course.find("f"))
print(course.find("o"))
print(course.find("r"))
print(course.find("B"))
print(course.find("e"))
print(course.find("g"))
print(course.find("n"))
print(course.find("n"))
print(course.find("e"))
print(course.find("r"))
print(course.find("s"))
