course = "Chess for Beginners"
print(course[0])
print(course[1])
print(course[2])
print(course[3])
print(course[4])
print(course[5])
print(course[6])
print(course[7])
print(course[8])
print(course[9])
print(course[11])
print(course[12])
print(course[13])
print(course[14])
print(course[15])
print(course[16])
print(course[17])
print(course[18])
print("\n" + course)
